### PR TITLE
Ro cmes real plume configs

### PR DESCRIPTION
**Pull request by rsparkyc**
This merges master into your branch, and also contains the MODEL_MULTI_SHURIKEN_PERSIST fix

### CODE REVIEW

**Comment by PhineasFreak** [comment]
I took care of it. Resolving conflicts is harder than closing and reopening a PR (and in that case is is a simple copy & paste operation).

Really appreciate the fact that you took your time to update all the RealPlume configs! Thank you for that!

**Comment by rsparkyc** [comment]
Actually, the merge conflicts weren't really that bad.  Just so you have some context as to where I'm coming from, I'm a tech lead at an online advertising company, and am pretty much dealing with PRs and merge conflicts all day.  This PR had me merging master into your branch and resolving the conflicts.  The only conflicts were where you update the formatting (which looks much better now) in the same code block where I made the line endings consistent.  Resolving the conflicts literally took 5 minutes :)

If this were then merged into your branch, your PR to the main RO repo would no longer have the conflicts, and everything should just "work".  

(FYI, I hope this didn't come across and rude or arrogant, just trying to help speed stuff up)

**Comment by PhineasFreak** [comment]
No, it's OK! You have a better background on dealing with stuff like that than me and so my decision to "brute force" the things.

Because i am also a slow learner i never really understood how to deal with them properly. Every time that i tried to resolve a confict it was a disaster. So, when things break because of them, i just remake the PRs. It is stupid but it works!

**Comment by rsparkyc** [comment]
Ok, cool, as you can imagine, it's hard to tell people's tone over just a text conversation :)  Some merge conflicts can really be a pain, but I found want really helps me is using a good tool.  I use sourcetree to work with Git, and I find that helps give me a sense of everything that's been changed much better.  Your other PR looks good, seems to have no differences then what this would have, so while I haven't actually tested it (since I'm still trying to figure out HOW to get to a spot where I can test stuff), I'd say it LGTM.

**Pull request closed without merging**
